# Generated by Django 5.1 on 2024-11-19 11:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studystreak_watchhistory'),
        ('tutor', '0019_tutorslot_tutorslotratehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WatchHistory',
            new_name='StudyActivity',
        ),
    ]
