# Generated by Django 5.1 on 2024-11-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_watchhistory_studyactivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyactivity',
            old_name='watch_time',
            new_name='watch_duration',
        ),
        migrations.AddField(
            model_name='studystreak',
            name='total_study_days',
            field=models.IntegerField(default=0),
        ),
    ]
