# Generated by Django 5.1 on 2024-11-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_call', '0002_alter_videocallrequest_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocallrequest',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
