# Generated by Django 5.1 on 2024-11-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_call', '0003_videocallrequest_scheduled_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocallrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
