name: Backend CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'Server/**'  # Only trigger on changes in Server directory
  pull_request:
    branches: [ main ]
    paths:
      - 'Server/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: Server  # Set working directory to Server

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./Server  # Specify Server directory
        file: ./Server/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/lexiwaves:latest