# Generated by Django 5.1 on 2024-09-09 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_tutorotpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('degrees', models.CharField(blank=True, max_length=255, null=True)),
                ('certifications', models.CharField(blank=True, max_length=255, null=True)),
                ('educational_institutions', models.CharField(blank=True, max_length=255, null=True)),
                ('relevant_courses', models.CharField(blank=True, max_length=255, null=True)),
                ('work_history', models.TextField(blank=True, null=True)),
                ('current_position', models.CharField(blank=True, max_length=255, null=True)),
                ('teaching_experience', models.TextField(blank=True, null=True)),
                ('subjects_offered', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_levels', models.CharField(blank=True, max_length=255, null=True)),
                ('teaching_license', models.FileField(blank=True, null=True, upload_to='teaching_licenses/')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('payment_methods', models.CharField(blank=True, max_length=255, null=True)),
                ('personal_statement', models.TextField(blank=True, null=True)),
                ('identity_proof', models.FileField(blank=True, null=True, upload_to='identity_proofs/')),
                ('terms_of_service', models.BooleanField(default=False)),
                ('privacy_policy', models.BooleanField(default=False)),
                ('admin_approved', models.BooleanField(default=False)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tutor.tutor')),
            ],
        ),
    ]
