# Generated by Django 5.1 on 2024-09-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_remove_tutordetails_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='admin_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
