# Generated by Django 5.1 on 2024-09-11 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_tutor_admin_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='admin_approved',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='password',
        ),
        migrations.AddField(
            model_name='tutor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
