# Generated by Django 5.1 on 2024-09-11 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_remove_tutor_admin_approved_remove_tutor_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='user',
            new_name='tutor',
        ),
        migrations.AddField(
            model_name='tutordetails',
            name='tutor',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='tutor.tutor'),
            preserve_default=False,
        ),
    ]
