# Generated by Django 5.1 on 2024-09-11 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_rename_user_tutor_tutor_tutordetails_tutor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='tutor',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='tutordetails',
            name='tutor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutor.tutor'),
        ),
    ]
