# Generated by Django 5.1 on 2024-09-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0009_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail_url',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='course',
            name='video_url',
            field=models.TextField(max_length=1000),
        ),
    ]
