# Generated by Django 5.1 on 2024-09-24 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0011_course_is_approved_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='video_url',
            new_name='preview_url',
        ),
    ]
