# Generated by Django 5.1 on 2024-10-06 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0014_rename_video_url_lesson_lesson_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutordetails',
            name='payment_methods',
        ),
        migrations.RemoveField(
            model_name='tutordetails',
            name='privacy_policy',
        ),
        migrations.RemoveField(
            model_name='tutordetails',
            name='teaching_license',
        ),
    ]
