# Generated by Django 5.1 on 2024-10-06 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0015_remove_tutordetails_payment_methods_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutordetails',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='tutordetails',
            name='relevant_courses',
        ),
    ]
