# Generated by Django 5.1 on 2024-09-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexi_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
