# Generated by Django 5.1 on 2024-09-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexi_admin', '0003_studentcourseenrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourseenrollment',
            name='payment_status',
            field=models.CharField(default='successful', max_length=20),
        ),
    ]
