# Generated by Django 5.1 on 2024-09-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexi_admin', '0004_alter_studentcourseenrollment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourseenrollment',
            name='payment_status',
            field=models.CharField(default='complete', max_length=20),
        ),
    ]
