# Generated by Django 5.1 on 2024-11-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexi_admin', '0009_rename_coruse_adminrevenue_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrevenue',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
