version: '3.8'

services:
  backend:
    image: ${DOCKERHUB_USERNAME}/lexiwaves-backend:latest
    restart: always
    env_file: .env
    depends_on:
      - db
      - redis
    command: >
      sh -c "
        python manage.py migrate &&
        gunicorn lexiWaves.wsgi:application --bind 0.0.0.0:8000
      "

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend


  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: