# Generated by Django 5.1 on 2024-10-09 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('lexi_admin', '0006_alter_studentcourseenrollment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lexi_admin.language'),
        ),
    ]
