name: LexiWaves CD

on:
  workflow_run:
    workflows: ['LexiWaves CI']
    types:  
      - completed
    branches:
      - main

jobs:
  docker-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Shallow clone - only latest commit
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2  
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./Server
          file: ./Server/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/lexiwaves-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/lexiwaves-backend:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/lexiwaves-backend:latest
          cache-to: type=inline
          platforms: linux/amd64

  