name: LexiWaves CI

on:
  push:
    branches: [main]
    paths:
      - 'Server/**'

jobs:
  analyze-and-build:
    runs-on: ubuntu-latest


    services:
        postgres:
          image: postgres:latest
          env:
            POSTGRES_DB: ${{ secrets.DB_NAME }}
            POSTGRES_USER: ${{ secrets.DB_USER }} 
            POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          ports:
            - 5432:5432
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Create env file  
        run: |
          cd Server
          echo "${{ secrets.ENV_FILE }}" > .env


      - name: Install dependencies
        run: |
          cd Server
          pip install -r requirements.txt

          
      - name: Run tests with coverage
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: localhost 
          DB_PORT: 5432
        run: |
          cd Server
          pytest  \
            accounts/tests/ \
            lexi_admin/tests/ \
            --cov=accounts \
            --cov=lexi_admin \
            --cov-report=xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=your_project_key
            -Dsonar.sources=.
            -Dsonar.coverageReportPaths=coverage.xml

  build-and-push:
    needs: analyze-and-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build & Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./Server
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/lexiwaves-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/lexiwaves-backend:${{ github.sha }}