name: LexiWaves CI

on:
  push:
    branches: [main]
    paths:
      - 'Server/**'
      # - 'frontend/**'  # Add frontend path

jobs:
  analyze-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          cd Server
          pip install -r requirements.txt

          
      - name: Run tests with coverage
        run: |
          cd Server
          pytest --cov=. --cov-report=xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
  build-and-push:
    needs: analyze-and-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build & Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./Server
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/lexiwaves-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/lexiwaves-backend:${{ github.sha }}
            
      # - name: Build & Push Frontend
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: ./frontend
      #     push: true
      #     tags: |
      #       ${{ secrets.DOCKERHUB_USERNAME }}/lexiwaves-frontend:latest
      #       ${{ secrets.DOCKERHUB_USERNAME }}/lexiwaves-frontend:${{ github.sha }}